---
components:
  examples: {}
  headers: {}
  parameters: {}
  requestBodies: {}
  responses: {}
  schemas: {}
  securitySchemes: {}
info:
  title: '@grpc/producer'
  version: '0.0.1'
  description: 'gRPC Producer'
  license:
    name: 'MIT'
  contact:
    name: 'hieudoanm '
    email: 'hieumdoan@gmail.com'
openapi: '3.0.0'
paths:
  /health:
    get:
      operationId: 'Get'
      responses:
        200:
          description: 'Ok'
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: 'string'
                required:
                  - 'status'
                type: 'object'
      tags:
        - 'Health'
      security: []
      parameters: []
servers:
  - url: '/'
